services:
  # Main application
  elderly-care-engine:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_PATH=sqlite:///./data/rules.db
      - BROKER_HOST=mosquitto
      - BROKER_PORT=1883
    volumes:
      - ../src:/app/src
      - ../data:/app/data
      - ../.env:/app/.env
    depends_on:
      - mosquitto
    networks:
      - elderly-care-network
    restart: unless-stopped

  # MQTT Broker
  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - elderly-care-network
    restart: unless-stopped

  # Optional: Database (if you want to use PostgreSQL instead of SQLite)
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: elderly_care
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - elderly-care-network
  #   restart: unless-stopped

volumes:
  mosquitto_data:
  mosquitto_logs:
  # postgres_data:  # Uncomment if using PostgreSQL

networks:
  elderly-care-network:
    driver: bridge